export const BRANDS = [
  "Nike",
  "Adidas",
  "Puma",
  "Zara",
  "H&M",
  "Levi's",
  "Uniqlo",
  "Mango",
  "Calvin Klein",
  "Tommy Hilfiger",
  "Under Armour",
  "Reebok",
  "New Balance",
  "Asics",
  "Converse",
  "Vans",
  "Fila",
  "Skechers",
  "Lacoste",
  "Diesel",
  "Gap",
  "Forever 21",
  "Jack & Jones",
  "Only",
  "Vero Moda",
  "Pepe Jeans",
  "Superdry",
  "American Eagle",
  "The North Face",
  "Columbia",
  "Wrangler",
  "Lee",
  "Allen Solly",
  "Van Heusen",
  "Louis Philippe",
  "Peter England",
  "Roadster",
  "Wrogn",
  "HRX",
  "U.S. Polo Assn.",
  "Arrow",
  "United Colors of Benetton",
  "Flying Machine",
  "Marks & Spencer",
  "FabIndia",
  "Biba",
  "Max Fashion",
  "Pantaloons",
  "Decathlon",
  "Campus",
] as const;

export const SIZE_OPTIONS = ["S", "M", "L", "XL", "XXL", "3XL", "4XL"] as const;
